version: "3.8"
services:
  backend:
    build: ./docker/php
    volumes:
      - ./backend:/backend
    tty: true

  frontend:
    build: ./docker/node
    volumes:
      - ./frontend:/frontend
    command: sh -c "npm run dev"
    ports:
      - "3000:3000"
    tty: true

  nginx:
    image: nginx
    volumes:
      - ./backend:/backend
      - ./logs:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  db:
    build: ./docker/db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - db-store:/var/lib/mysql
    ports:
      - "3306:3306"
    tty: true

  php-my-admin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - "89:80"
    environment:
      MYSQL_USERNAME: test
      MYSQL_ROOT_PASSWORD: test
      PMA_HOST: db
      PMA_PORT: 3306

volumes:
  db-store:
